# Generated by Django 4.2.1 on 2023-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_cart_products_remove_cart_quantity_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='carts', to='app1.product'),
        ),
    ]
